# Generated by Django 6.0.7 on 2026-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Kids Learning', max_length=100)),
                ('app_logo', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#4CAF50', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='The app is temporarily under maintenance.')),
                ('enable_screen_time', models.BooleanField(default=False)),
                ('enable_watch_history', models.BooleanField(default=False)),
                ('enable_parent_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
