# Generated by Django 6.0.7 on 2026-07-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('ADMIN', 'Admin')], default='PARENT', max_length=10),
        ),
    ]
